export const CASE_GET_PRODUCTS = "GET_PRODUCTS";
export const CASE_GET_ONE_PRODUCT = "GET_ONE_PRODUCT";

export const CASE_GET_BRANDS = 'GET_BRANDS';

export const CASE_GET_COMMENTS = 'GET_COMMENTS';

export const CASE_GET_CART = "GET_CART";

export const CASE_GET_FAVORITES = "GET_FAVORITES";

export const CASE_GET_LIKE = "GET_LIKE";

export const REMOVE_CART = "REMOVE_CART";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";

